services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: development
    ports:
      - 3000:3000
    networks:
      - mern-dockerized-network
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm run dev
  database:
    image: mongo:8.0
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
    ports:
      - 27017:27017
    expose:
      - 27017
    networks:
      - mern-dockerized-network
    volumes:
      - ./database/db:/data/db
      - ./database/dev.archive:/Databases/dev.archive
      - ./database/production:/Databases/production
  database-ui:
    image: mongo-express
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_URL=mongodb://root:password@database:27017/?authSource=admin
      - ME_CONFIG_BASICAUTH_USERNAME=mexpress
      - ME_CONFIG_BASICAUTH_PASSWORD=mexpress
    links:
      - database
    ports:
      - 8081:8081
    networks:
      - mern-dockerized-network
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: build
    environment:
      - DB_USERNAME=root
      - DB_PASSWORD=password
    volumes:
      - ./backend:/app
      - /app/node_modules
    ports:
      - 4000:4000
    networks:
      - mern-dockerized-network
    command: npm run dev
networks:
  mern-dockerized-network:
    driver: bridge
